### ISSUE TITLE
No valid host due to memory

### ISSUE THREAD

**Issue by ryan-beisner** [openstack-charmers/openstack-on-lxd#17]
On a host with 32GB RAM, after the openstack-on-lxd model is deployed (Juju 2.2b1), there is less than 1GB mem available on the host.  When an instance is created with an m1.small, it enters and ERROR state and the scheduler shows no valid host.

Because this is a developer-centric bundle, and an all-on-one OpenStack cloud (non-HA, limited resources) is not considered production, it should be reasonable to raise the memory overcommit levels.

**Comment by andrewdmcleod** [comment]
Agree, additionally, is it worth considering that the memory size for the m1.small flavor could (also) be decreased?
