### ISSUE TITLE
bundle-newton-s390x failing with: cpu-allocation-ratio expected float, got 64"

### ISSUE THREAD

**Issue by scheuran** [openstack-charmers/openstack-on-lxd#18]
This happens when deploying the bundle 

> juju deploy bundle-newton-s390x.yaml

ERROR cannot deploy bundle: cannot deploy application "nova-cloud-controller": option "cpu-allocation-ratio" expected float, got 64

Probably it's related to commit [1]

[1] https://github.com/openstack-charmers/openstack-on-lxd/commit/36d91253dd38deab1579233e196dfdd2f675775b

**Comment by scheuran** [comment]
This is not working:

`ram-allocation-ratio: 64.0`

But this works:

```
ram-allocation-ratio: "64.0"
cpu-allocation-ratio: "64.0"
```

Haven't tried just "64"

**Comment by afreiberger** [comment]
addressed by PR #26.

Bug is actually in juju deploy bundle.  See: https://pad.lv/1613839

**Comment by ryan-beisner** [comment]
Please see underlying bug:  https://bugs.launchpad.net/juju/+bug/1613839
