### ISSUE TITLE
bundle-bionic-rocky.yaml: ceilometer-agent needs RMQ relation (or gets blocked)

### ISSUE THREAD

**Issue by auria** [openstack-charmers/openstack-on-lxd#63]
After deploying `bundle-bionic-rocky.yaml`, ceilometer-agent gets blocked because of missing Messaging relation. After relating it to rabbitmq-server, ceilometer-agent went into active/idle.

**Comment by lourot** [comment]
Same problem with `bundle-xenial-{newton,pike,queens}.yaml`:

```
$ juju deploy ./bundle-xenial-pike.yaml
$ juju status | grep blocked
ceilometer-agent       9.0.6    blocked  ceilometer-agent  jujucharms  258  ubuntu
  ceilometer-agent/0*  blocked  idle     xxx.xxx.xxx.xxx   Missing relations: messaging
```
