### ISSUE TITLE
Docs: Add note for setting "export OS_AUTH_URL=http://<....>" when no ssl specified

### ISSUE THREAD

**Issue by robinbraemer** [openstack-charmers/openstack-on-lxd#78]
When following this docs until step https://docs.openstack.org/charm-guide/latest/openstack-on-lxd.html#deploy-the-cloud
I loaded the env with `source openrcv3_project`, but when running a client command such as `openstack catalog list` there is this error:
```
Failed to discover available identity versions when contacting https://10.170.140.112:5000/v3. Attempting to parse version from URL.
SSL exception connecting to https://10.170.140.112:5000/v3/auth/tokens: HTTPSConnectionPool(host='10.170.140.112', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))
```

Maybe the docs should also be updated for this error case.
OpenStack is fully running on my single machine, how can I fix this SSL error?

**Comment by robinbraemer** [comment]
Okey so the issue was that there is no ssl/https and I needed to update the `OS_AUTH_UR` to use http.
So after loading `source openrcv3_project` I needed to set it to `export OS_AUTH_URL=http://<....>/<...>`.

Could a maintainer please add a note in the docs that one has to do this if no ssl is specified?

**Comment by rgildein** [comment]
I encountered the same problem and it is caused by an error in this line https://github.com/openstack-charmers/openstack-on-lxd/blob/4d470183d54e2552d11ad45d0bf53ba29c672fff/openrcv3_project#L15.

If the variable `_root_ca` is not present, then this condition should not set` OS_AUTH_PROTOCOL` to https.
